// export constant
export const SET_DISCHARGE = "SET_DISCHARGE";
export const SET_LOADED = "SET_LOADED";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

export const ADD_PIZZA_CART = "ADD_PIZZA_CART";
export const ADD_PIZZA_CART_ERROR = "ADD_PIZZA_CART_ERROR";

export const CLEAR_PIZZA_ITEMS = "CLEAR_PIZZA_ITEMS";
export const CLEAR_PIZZA_ITEMS_ERROR = "CLEAR_PIZZA_ITEMS_ERROR";

export const CLEAR_PIZZA_ITEM = "CLEAR_PIZZA_ITEM";
export const CLEAR_PIZZA_ITEM_ERROR = "CLEAR_PIZZA_ITEM_ERROR";

export const PLUS_CART_ITEM = "PLUS_CART_ITEM";
export const PLUS_PIZZA_CART_ITEM_ERROR = "PLUS_PIZZA_CART_ITEM_ERROR";

export const MINUS_CART_ITEM = "MINUS_CART_ITEM";
export const MINUS_PIZZA_CART_ITEM_ERROR = "MINUS_PIZZA_CART_ITEM_ERROR";
